name: estate_management
description: Residental Management System for InforceBT

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #state
  flutter_riverpod: ^2.3.6

  #route
  auto_route: ^5.0.4

  #db
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  auto_route_generator: ^5.0.3
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
